language: ruby
rvm:
  - 2.1.5
  - 2.2.1
install:
  - sudo apt-get purge virtualbox
  - sudo apt-get install -q libsdl1.2debian libvpx1
#  - sudo wget -nv http://download.virtualbox.org/virtualbox/5.0.8/virtualbox-5.0_5.0.8-103449~Ubuntu~trusty_amd64.deb
#  - sudo dpkg -i virtualbox-5.0_5.0.8-103449~Ubuntu~trusty_amd64.deb
  - sudo wget -nv http://download.virtualbox.org/virtualbox/5.0.8/VirtualBox-5.0.8-103449-Linux_amd64.run
  - chmod +x VirtualBox-5.0.8-103449-Linux_amd64.run && sudo ./VirtualBox-5.0.8-103449-Linux_amd64.run
  - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb
  - sudo dpkg -i vagrant_1.7.4_x86_64.deb
  - bundle install
script: bundle exec rspec spec/acceptance
