#!/bin/sh
#
# Contain Environment variables for installs
#

HOME_DIR="/home/vagrant"

SHARED_DIR="/vagrant"

DOWNLOAD_DIR="$SHARED_DIR/downloads"
if [ ! -d $DOWNLOAD_DIR ]; then
  mkdir $DOWNLOAD_DIR
fi

FEDORA_VERSION=4.7.1-RC-1
FEDORA_TAG=4.7.1-RC-1
# true to enable auth, false to disable it
FEDORA_AUTH=true
FEDORA_AUDIT=true
FEDORA_AUDIT_LOCATION=/audit
